<a href="https://colab.research.google.com/github/SUPAGORN0306/229352-StatisticalLearning/blob/main/Lab08_670510771_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a = torch.tensor(2)
a

tensor(2)

In [ ]:
b = torch.tensor(3)
b

tensor(3)

### Convert a tensor to scalar

In [ ]:
c = b.item
c

<function Tensor.item>

### Creating 2D tensor

In [ ]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
B = A.numpy
B

<function Tensor.numpy>

### Convert from numpy array to tensor

In [ ]:
C = torch.from_numpy(B())

## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

In [ ]:
C.device

device(type='cpu')

In [ ]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [ ]:
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [ ]:
E*2

array([[ 2,  4],
       [10, 12]])

In [ ]:
D-2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [ ]:
D.cpu() * np.array([1, 2])

/tmp/ipython-input-4124694458.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [ ]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])
torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
A@B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [ ]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [ ]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
R1 = torch.rand(2, 3)
R1

tensor([[0.6531, 0.6462, 0.8560],
        [0.4540, 0.8404, 0.5985]])

In [ ]:
R2 = torch.randn(2, 3)
R2

tensor([[-0.0405, -0.6600,  1.0565],
        [ 0.4684, -2.0810, -1.8677]])

In [ ]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

In [ ]:
A.shape

torch.Size([2, 2])

In [ ]:
A.size

<function Tensor.size>

### Checking the shape of a tensor

In [ ]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [ ]:
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

### Changing the shape of a tensor

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
a = torch.arange(4)
b = torch.arange(4)
c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3]])

In [ ]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [ ]:
# concatenate
e = torch.cat([a, b], axis=0)
e

tensor([0, 1, 2, 3, 0, 1, 2, 3])

In [ ]:
f = torch.cat([a, b], axis=1)
f

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [ ]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
C.shape

torch.Size([1, 2, 3])

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [ ]:
P[[0, 1], [0, 1]]
P[0:3, 0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [ ]:
torch.inverse(torch.tensor([[2.0,0.0], [0.0,5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
A**2

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
A.sum()

tensor(0.)

In [ ]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [ ]:
X = torch.randn(200, 7, dtype=torch.float64)
print(X)

tensor([[-0.3674,  0.9604,  0.2008,  ..., -1.0801, -1.0610,  0.4641],
        [ 0.5696, -0.5706,  0.7915,  ...,  0.1937,  0.4115, -0.0956],
        [-0.9547, -0.5701, -1.1982,  ...,  0.4744,  0.6165, -0.2877],
        ...,
        [-1.0400,  2.1571,  0.9682,  ...,  0.1616, -0.4854,  1.8187],
        [ 0.0428, -0.1285,  0.3499,  ..., -0.2216, -1.7054, -0.0840],
        [ 0.0328,  1.4409,  1.0659,  ...,  1.6793, -0.5078,  0.6474]],
       dtype=torch.float64)


In [ ]:
b = torch.randn(8, 1, dtype=torch.float64)
print(b)

tensor([[ 0.0448],
        [-0.3884],
        [ 0.6969],
        [-1.6560],
        [-0.4567],
        [ 1.0574],
        [ 1.0511],
        [-0.4825]], dtype=torch.float64)


In [ ]:
e = torch.randn(200, 1, dtype=torch.float64)
print(e)

tensor([[ 0.2686],
        [ 1.0398],
        [-0.2934],
        [-0.6340],
        [ 1.2074],
        [ 0.1058],
        [-0.5658],
        [ 0.7991],
        [ 2.5113],
        [-0.0283],
        [-1.3280],
        [-0.5158],
        [ 0.7035],
        [-0.8520],
        [-0.3412],
        [-0.7694],
        [ 0.4353],
        [ 0.3721],
        [ 0.7708],
        [-0.1295],
        [ 0.2032],
        [-1.7012],
        [-0.6378],
        [ 0.9384],
        [-0.3165],
        [-0.7094],
        [ 0.8512],
        [-0.5543],
        [-0.3219],
        [ 0.1821],
        [ 0.8508],
        [-0.9572],
        [-0.1505],
        [-0.4426],
        [-1.6558],
        [-0.6568],
        [ 0.5230],
        [-0.7818],
        [ 0.7193],
        [ 0.8871],
        [ 0.1225],
        [-1.2542],
        [-0.9073],
        [ 0.2579],
        [ 1.2707],
        [ 0.5180],
        [-1.7452],
        [-0.5962],
        [ 0.7516],
        [-0.0881],
        [ 0.6388],
        [-1.2462],
        [-0.

In [ ]:
t = torch.ones(200, 1, dtype=torch.float64)
print(t)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [ ]:
X = torch.cat([t, X], dim=1)
print(X)
print(X.shape)

tensor([[ 1.0000, -0.3674,  0.9604,  ..., -1.0801, -1.0610,  0.4641],
        [ 1.0000,  0.5696, -0.5706,  ...,  0.1937,  0.4115, -0.0956],
        [ 1.0000, -0.9547, -0.5701,  ...,  0.4744,  0.6165, -0.2877],
        ...,
        [ 1.0000, -1.0400,  2.1571,  ...,  0.1616, -0.4854,  1.8187],
        [ 1.0000,  0.0428, -0.1285,  ..., -0.2216, -1.7054, -0.0840],
        [ 1.0000,  0.0328,  1.4409,  ...,  1.6793, -0.5078,  0.6474]],
       dtype=torch.float64)
torch.Size([200, 8])


$$ y = Xb + e $$

In [ ]:
y = (X@b)+e
print(y)
print(y.shape)

tensor([[-1.2790e+00],
        [ 2.1350e-01],
        [ 2.6608e+00],
        [-3.7875e+00],
        [ 2.6741e+00],
        [-5.7829e+00],
        [-2.0632e+00],
        [-1.5734e+00],
        [ 7.6167e+00],
        [ 7.9260e-01],
        [-2.9188e+00],
        [-3.2511e-01],
        [ 3.6754e-01],
        [-2.7147e+00],
        [-3.4788e+00],
        [ 1.0272e+00],
        [-6.5963e-01],
        [-1.2952e+00],
        [-5.1852e-01],
        [-2.3718e+00],
        [ 7.0243e-01],
        [-2.5107e+00],
        [ 1.1154e+00],
        [ 2.0168e+00],
        [-1.0989e+00],
        [-4.9194e+00],
        [ 4.7593e+00],
        [ 4.3707e+00],
        [-1.5062e-01],
        [-3.7190e+00],
        [-1.6401e+00],
        [-6.3419e-01],
        [ 3.2217e+00],
        [-2.5182e-01],
        [-1.9662e+00],
        [ 3.1748e+00],
        [-3.5509e+00],
        [-9.2938e-01],
        [-3.2340e+00],
        [-3.0837e+00],
        [ 1.2133e+00],
        [ 6.4968e-01],
        [-1.3312e-01],
        [ 9

$$ \hat{b} = (X^TX)^{-1}X^Ty $$

In [ ]:
b_hat = torch.inverse(X.T@X)@X.T@y
print(b_hat)

tensor([[ 0.0262],
        [-0.4185],
        [ 0.5857],
        [-1.7450],
        [-0.4735],
        [ 1.0718],
        [ 1.1178],
        [-0.3298]], dtype=torch.float64)


$$ \hat{y} = X\hat{b} $$

In [ ]:
y_hat = X@b_hat
print(y_hat)
print(y_hat.shape)

tensor([[-1.6803],
        [-0.8396],
        [ 3.1259],
        [-3.2983],
        [ 1.4837],
        [-5.8533],
        [-0.9115],
        [-2.2699],
        [ 5.6229],
        [ 0.6016],
        [-1.9785],
        [ 0.0598],
        [-0.1604],
        [-2.0347],
        [-3.2896],
        [ 1.6516],
        [-1.0079],
        [-1.8257],
        [-1.0702],
        [-2.3191],
        [ 0.2834],
        [-0.5285],
        [ 1.8448],
        [ 1.2590],
        [-0.6347],
        [-4.3272],
        [ 4.0488],
        [ 4.9828],
        [ 0.2967],
        [-4.2227],
        [-2.4448],
        [ 0.2957],
        [ 3.1602],
        [ 0.4244],
        [-0.5376],
        [ 3.9655],
        [-4.1294],
        [-0.1906],
        [-3.9473],
        [-4.2447],
        [ 1.0907],
        [ 1.7451],
        [ 0.8039],
        [ 0.3875],
        [ 1.5800],
        [-0.5530],
        [ 2.5014],
        [ 0.4034],
        [ 1.8369],
        [-4.6883],
        [-0.6822],
        [ 1.4417],
        [-4.

In [ ]:
arr_y = y[:,0].numpy()
arr_y_hat = y_hat[:,0].numpy()

In [ ]:
MSE = np.mean(np.square(arr_y - arr_y_hat))
print(MSE)

0.8337186911822546
